// export const REGISTER = 'REGISTER';
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const MESSAGE_INIT = "MESSAGE_INIT";
export const MESSAGE_FETCH_SUCCESS = "MESSAGE_FETCH_SUCCESS";
export const MESSAGE_FETCH_FAIL = "MESSAGE_FETCH_FAIL";

export const MESSAGE_SEND_START = "MESSAGE_SEND_START";
export const MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS";
export const MESSAGE_SEND_FAIL = "MESSAGE_SEND_FAIL";

export const LOGOUT = 'LOGOUT';
export const AUTO_SIGN = 'AUTO_SIGN';